name: Main

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.platform }}

    steps:

    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

    - run: nix build .#tests.build .#tests.kernel-tests.core
