name: CI

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.platform }}

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Flake check
      run: |
        nix build \
           .#jupyterEnvironment \
           .#build \
           .#core \
           --accept-flake-config --show-trace
