name: nix-macos

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: |
        nix-env -i cachix
        cachix use jupyterwith
        nix-build tests -A build
#    - uses: cachix/cachix-action@v2
#      with:
#        name: jupyterwith
#        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
