name: "nix-flake"
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

    - run: |
        cd example/flake
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        echo $BRANCH_NAME
        nix flake lock --override-input jupyterWith ../..
        nix -Lv develop . --command echo OK
