name: nix-macos

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v10
      with:
        name: jupyterwith
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - run: nix-build tests -A build -A kernel-tests.core
